export const metadata = {
  title:{
    //absolute:'', not required here check /docs/[...slug] route
    default:"Default description", // fallback title incase routesegement doesn't have title metadata eg for blog
    template:'%s | rootlayout'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <header style={{backgroundColor:'lightblue' , padding:'1rem'}}>
        <p>Header</p>
      </header>
      {children}
      <footer style={{backgroundColor:'ghostwhite' , padding:'1rem'}}>
        <p>Footer</p>
      </footer>
      </body>
    </html>
  )
}
 